export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
        </header>

        {children}
        
        <footer
          style={{
            backgroundColor: "lightgreen",
            padding: "1rem",
          }}
        >
        </footer>
      </body>
    </html>
  );
}
